app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
App::missing(function($exeption){
return Response::view('layout.error404');
});
App::after(function($request, $response)
{
$response->headers->set('Cache-Control','nocache, no-store, max-age=0, must-revalidate');
$response->headers->set('Pragma','no-cache');
$response->headers->set('Expires','Fri, 01 Jan 1990 00:00:00 GMT');
});
// Home
Route::get  ('/','HomeController@index');
Route::get  ('/jugadores','HomeController@players');
Route::get  ('/galeria','HomeController@gallery');
Route::get  ('/noticia/{id}','HomeController@noticia');
Route::get  ('/noticias','HomeController@noticias');
Route::get  ('/estadisticas','HomeController@estadisticas');
Route::get  ('/login','HomeController@login');
Route::post ('/loged', 'UsersController@loged');
Route::get  ('/logout', 'UsersController@logout');
// Administracion
Route::group(array('before' => 'Sentry|inGroup:admin'), function(){
	Route::resource('/admin/cancha', 'CanchasController');
	Route::resource('/admin/categoria', 'CategoriasController');
	Route::resource('/admin/equipo', 'EquiposController');
	Route::resource('/admin/torneo', 'TorneosController');
	Route::resource('/admin/noticia', 'NoticiasController');
	Route::resource('/admin/jugador', 'JugadoresController');
	Route::get     ('/admin/jugador/{id}/baja', 'JugadoresController@baja');
	Route::resource('/admin/slider', 'SlidersController');
	Route::resource('/admin/galeria', 'GaleriasController');
	Route::resource('/admin/partido','PartidosController');
	Route::resource('/admin/goleador','GoleadoresController');
	Route::resource('/admin/marcador','MarcadoresController');
	Route::resource('/admin/posicion','PosicionesController');
	Route::get  ('/admin/resultado/visitantes/{id}','ResultadosController@visitantes');
	Route::get  ('/admin/resultado/fecha/{id}','ResultadosController@fecha');
	Route::get   ('/admin/noticia/progress/{id}','NoticiasController@progress');
});

app/models/Slider.php
<?php

class Slider extends \Eloquent {
	protected $fillable = [];
}

app/controllers/SlidersController.php
<?php

class SlidersController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 * GET /sliders
	 *
	 * @return Response
	 */
	public function index()
	{
		$sliders  = Slider::all();
		return View::make('slider.index')
		->with('sliders',$sliders);
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /sliders/create
	 *
	 * @return Response
	 */
	public function create()
	{
		return Redirect::to('admin/slider');
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /sliders
	 *
	 * @return Response
	 */
	public function store()
	{
		return Redirect::to('admin/slider');
	}

	/**
	 * Display the specified resource.
	 * GET /sliders/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$slider = Slider::find($id);
		return View::make('slider.show')
		->with('slider',$slider);
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /sliders/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$slider = Slider::find($id);
		return View::make('slider.edit')
		->with('slider',$slider);
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /sliders/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$destino  = public_path().'/src/slider/';
		if (Input::file('imagen')) {
			$extension = Input::file('imagen')->getClientOriginalExtension();
			if ($extension == "jpg") {
				$imagen    = $id.'s.jpg';
				$file      = Input::file('imagen');
				$img = Image::make($file->getRealPath());
				$img->resize(945, null, function ($constraint) {
				     $constraint->aspectRatio();
				 })->crop(945, 420)->save($destino.$imagen);
				$img->resize(189, null, function ($constraint) {
				     $constraint->aspectRatio();
				 })
				->crop(189, 84)->save($destino.'/miniaturas/'.$imagen);
				$tipo = 'alert-success';
				$mensaje ="La imagen actualizo correctamente";
			} else {
				$tipo = 'alert-danger';
				$mensaje ="La imagen debe de tener la extencion .jpg";
			}
		} else {
			$tipo = 'alert-warning';
			$mensaje ="No seleccionaste ninguna imagen";
		}
		Session::put($tipo, $mensaje);
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /sliders/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		return Redirect::to('admin/slider');
	}

}

app/views/slider/edit.blade.php
@extends('layout.main')
@section('title')
Editar Slider Imagen No. {{ $slider->id}} Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-user"></span> Editar Slider Imagen No. {{ $slider->id}}</h2>
		</div>
		<div class="panel-body">
			{{ Form::model($slider,array('method'=>'PUT', 'route' => array('admin.slider.update', $slider->id), 'files' => true)) }}
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-sm-offset-3">
					<div class="form-group">
						{{ Form::label('imagen')}}
						{{ Form::file('imagen', array('class'=>'form-control', 'required'=>'true'))}}<br>
					</div>
				<div class="progress">
					<div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
						<span class="sr-only">0% Complete (success)</span>
					</div>
				</div>
				</div>
		</div>
		<div class="panel-footer">
			<button type="submit" class="btn btn-success pull-right">Actualizar</button>
			<a class="btn btn-primary" href='{{ URL::previous() }}'>Regresar</a>
			{{ Form::close() }}
		</div>
	</div>
</div>
@stop
@section('js')
{{ HTML::script('js/form.js') }}
@stop
@section('script')
<script type="text/javascript">
	jQuery(document).ready(function($)
	{
		$('form').submit(function(event) {
			event.preventDefault();
			$(this).ajaxSubmit({
				uploadProgress:function(event, position, total, percentComplete) {
		            $('.progress-bar').css('width', percentComplete+'%');
		        },
		        complete:function(xhr) {
		            window.location="{{Url::to('/admin/slider')}}";
		        }
			});
		});
	});
</script>
@stop

app/views/slider/index.blade.php
@extends('layout.main')
@section('title')
Slider Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-md-offset-1 col-lg-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-th-large"></span> Slider</h2>
		</div>
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table">
					<thead>
						<tr>
							<th>Posición</th>
							<th>Imagen</th>
							<th>Acciones</th>
						</tr>
					</thead>
					<tbody>
						@foreach($sliders as $slider)
						<tr>
							<td>{{ $slider->id }}</td>
							<td>{{ HTML::image('src/slider/miniaturas/'.$slider->imagen.'.jpg', 'pumasruiz')}}</td>
							<td>
							{{ link_to_route('admin.slider.show','',$slider->id, array('class' => 'btn btn-success btn-xs glyphicon glyphicon-eye-open')) }}
							{{ link_to_route('admin.slider.edit','',$slider->id, array('class' => 'btn btn-info btn-xs glyphicon glyphicon-refresh')) }}
							</td>
						</tr>
					@endforeach
					</tbody>
				</table>
				<br><br>
			</div>
		</div>
	</div>
</div>
@stop
@section('css')
{{ HTML::style('css/toastr.css') }}
@stop
@section('js')
{{ HTML::script('js/toastr.js') }}
@stop
@section('script')
<script type="text/javascript">
	jQuery(document).ready(function($)
	{
		
	});
</script>
@stop

app/views/slider/show.blade.php
@extends('layout.main')
@section('title')
Slider Imagen No. {{ $slider->id}} Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-picture"></span> Slider Imagen No. {{ $slider->id}}</h2>
		</div>
		<div class="panel-body">
			{{ HTML::image('src/slider/'.$slider->imagen.'.jpg', 'pumasruiz',array('width' => '100%'))}}
			<br><br>
			<a class="btn btn-primary" href='{{ URL::previous() }}'>Regresar</a>
		</div>
	</div>
</div>
@stop