app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
App::missing(function($exeption){
return Response::view('layout.error404');
});
App::after(function($request, $response)
{
$response->headers->set('Cache-Control','nocache, no-store, max-age=0, must-revalidate');
$response->headers->set('Pragma','no-cache');
$response->headers->set('Expires','Fri, 01 Jan 1990 00:00:00 GMT');
});
// Home
Route::get  ('/','HomeController@index');
Route::get  ('/jugadores','HomeController@players');
Route::get  ('/galeria','HomeController@gallery');
Route::get  ('/noticia/{id}','HomeController@noticia');
Route::get  ('/noticias','HomeController@noticias');
Route::get  ('/estadisticas','HomeController@estadisticas');
Route::get  ('/login','HomeController@login');
Route::post ('/loged', 'UsersController@loged');
Route::get  ('/logout', 'UsersController@logout');
// Administracion
Route::group(array('before' => 'Sentry|inGroup:admin'), function(){
	Route::resource('/admin/cancha', 'CanchasController');
	Route::resource('/admin/categoria', 'CategoriasController');
	Route::resource('/admin/equipo', 'EquiposController');
	Route::resource('/admin/torneo', 'TorneosController');
	Route::resource('/admin/noticia', 'NoticiasController');
	Route::resource('/admin/jugador', 'JugadoresController');
	Route::get     ('/admin/jugador/{id}/baja', 'JugadoresController@baja');
	Route::resource('/admin/slider', 'SlidersController');
	Route::resource('/admin/galeria', 'GaleriasController');
	Route::resource('/admin/partido','PartidosController');
	Route::resource('/admin/goleador','GoleadoresController');
	Route::resource('/admin/marcador','MarcadoresController');
	Route::resource('/admin/posicion','PosicionesController');
	Route::get  ('/admin/resultado/visitantes/{id}','ResultadosController@visitantes');
	Route::get  ('/admin/resultado/fecha/{id}','ResultadosController@fecha');
	Route::get   ('/admin/noticia/progress/{id}','NoticiasController@progress');
});

app/models/Marcador.php
<?php

class Marcador extends \Eloquent {
    protected $table = 'marcadores';
    protected $fillable = [];

    public function scopeMarcadorPartido($query)
    {
        return $query
        ->join('partidos', 'partidos.id', '=', 'marcadores.partido_id')
        ->select(
            'partidos.torneo_id AS torneo',
            'partidos.dia AS dia',
            'marcadores.*'
            );
    }

    public function scopeEstadisticas($query)
    {

    }
    public function partido()
    {
        return $this->belongsTo('Partido');
    }

    public function equipo()
    {
        return $this->belongsTo('Equipo');
    }

	public function cancha()
    {
        return $this->belongsTo('Cancha');
    }
}

app/views/marcador/create.blade.php
@extends('layout.main')
@section('title')
Marcadoress Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-play"></span> Nuevo Marcadores</h2>
		</div>
		<div class="panel-body">
			{{ Form::open(array('route' => 'admin.marcador.store')) }}
				@include('marcador.form')
				<button type="submit" class="btn btn-success pull-right">Registrar</button>
				<a class="btn btn-primary" href='{{ URL::previous() }}'>Regresar</a>
			{{ Form::close() }}
		</div>
	</div>
</div>
@stop

app/views/marcador/edit.blade.php
@extends('layout.main')
@section('title')
Marcadoress Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-play"> Nuevo Marcadores</h2>
		</div>
		<div class="panel-body">
			{{ Form::model($marcador,array('method'=>'PUT', 'route' => array('admin.marcador.update', $marcador->id))) }}
				@include('marcador.form')
				<button type="submit" class="btn btn-success pull-right">Actualizar</button>
				<a class="btn btn-primary" href='{{ URL::previous() }}'>Regresar</a>
			{{ Form::close() }}
		</div>
	</div>
</div>
@stop

app/views/marcador/form.blade.php
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
	<div class="form-group">
		{{ Form::label('partido_id' , 'Partido')}}
		{{ Form::select('partido_id', $partidos, null, array('class'=>'form-control'))}}
	</div>
</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
	<div class="form-group">
		{{ Form::label('goles_f' , 'Goles a favor')}}
		{{ Form::select('goles_f', $goles, null, array('class'=>'form-control'))}}<br>
		{{ Form::label('goles_c' , 'Goles en contra')}}
		{{ Form::select('goles_c', $goles, null, array('class'=>'form-control'))}}<br>
	</div>
</div>

app/views/marcador/index.blade.php
@extends('layout.main')
@section('title')
Partidos Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-md-offset-1 col-lg-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-play"></span> Marcadores</h2>
			{{ HTML::link(URL::to('/admin/marcador/create'), '&nbsp;Nuevo', array('class' => 'btn btn-primary btn-sm pull-right glyphicon glyphicon-plus pull-right','style'=>'margin:-25px -10px 0 0')) }}
		</div>
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-hover" id="tabla">
					<thead>
						<tr>
							<th>vs Equipo</th>
							<th>Dia</th>
							<th>favor</th>
							<th>Contra</th>
							<th>Acciones</th>
						</tr>
					</thead>
					<tbody>
						@foreach($marcadores as $marcador)
						<tr>
							<td>{{ $marcador->partido->equipo->nombre }}</td>
							<td>{{ $marcador->dia }}</td>
							<td>{{ $marcador->goles_f }}</td>
							<td>{{ $marcador->goles_c }}</td>
							<td>
								{{ link_to_route('admin.marcador.show','',$marcador->id, array('class' => 'btn btn-success btn-xs glyphicon glyphicon-eye-open')) }}
								{{ link_to_route('admin.marcador.edit','',$marcador->id, array('class' => 'btn btn-warning btn-xs glyphicon glyphicon-pencil')) }}
								<a href="javascript:;" onclick="eliminaRegistro('{{URL::to('/admin/marcador/'.$marcador->id)}}','{{$marcador->id}}');" class="btn btn-danger btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="eliminar"><i class="glyphicon glyphicon-trash"></i></a>
								{{ Form::open(array('method' => 'DELETE', 'route' => array('admin.marcador.destroy', $marcador->id),'id'=>$marcador->id)) }}{{ Form::close() }}
							</td>
						</tr>
					@endforeach
					</tbody>
				</table>
				<br><br>
			</div>
		</div>
	</div>
</div>
@stop
@section('css')
{{ HTML::style('css/dataTables.bs.css') }}
@stop
@section('js')
{{ HTML::script('js/dataTables.js') }}
{{ HTML::script('js/dataTables.bs.js') }}
{{ HTML::script('js/toastr.js') }}
@stop
@section('script')
<script type="text/javascript">
	jQuery(document).ready(function($)
	{
		$('table').DataTable({
			"lengthMenu": [[5, 10, -1],[5, 10, 'Todo']]
		});
	});
</script>
@stop

app/views/marcador/show.blade.php
/@extends('layout.main')
@section('title')
{{ $marcador->nombre }} Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-play"></span> Marcador</h2>
		</div>
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>vs {{ $marcador->partido->equipo->nombre }}</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Goles a favor</td>
							<td>{{$marcador->goles_f}}</td>
						</tr>
						<tr>
							<td>Goles en contra:</td>
							<td>{{$marcador->goles_c}}</td>
						</tr>
						<tr>
							<td>Dia:</td>
							<td>{{$marcador->partido->dia}}</td>
						</tr>
						<tr>
							<td>Cancha:</td>
							<td>{{$marcador->partido->cancha->nombre}}</td>
						</tr>
						<tr>
							<td>Horario:</td>
							<td>{{$marcador->partido->horario}}</td>
						</tr>
						<tr>
							<td>Fecha:</td>
							<td>{{$marcador->partido->fecha}}</td>
						</tr>
					</tbody>
				</table>
			</div>
			<a class="btn btn-primary" href='{{ URL::previous() }}'>Regresar</a>
		</div>
	</div>
</div>
@stop