app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
App::missing(function($exeption){
return Response::view('layout.error404');
});
App::after(function($request, $response)
{
$response->headers->set('Cache-Control','nocache, no-store, max-age=0, must-revalidate');
$response->headers->set('Pragma','no-cache');
$response->headers->set('Expires','Fri, 01 Jan 1990 00:00:00 GMT');
});
// Home
Route::get  ('/','HomeController@index');
Route::get  ('/jugadores','HomeController@players');
Route::get  ('/galeria','HomeController@gallery');
Route::get  ('/noticia/{id}','HomeController@noticia');
Route::get  ('/noticias','HomeController@noticias');
Route::get  ('/estadisticas','HomeController@estadisticas');
Route::get  ('/login','HomeController@login');
Route::post ('/loged', 'UsersController@loged');
Route::get  ('/logout', 'UsersController@logout');
// Administracion
Route::group(array('before' => 'Sentry|inGroup:admin'), function(){
	Route::resource('/admin/cancha', 'CanchasController');
	Route::resource('/admin/categoria', 'CategoriasController');
	Route::resource('/admin/equipo', 'EquiposController');
	Route::resource('/admin/torneo', 'TorneosController');
	Route::resource('/admin/noticia', 'NoticiasController');
	Route::resource('/admin/jugador', 'JugadoresController');
	Route::get     ('/admin/jugador/{id}/baja', 'JugadoresController@baja');
	Route::resource('/admin/slider', 'SlidersController');
	Route::resource('/admin/galeria', 'GaleriasController');
	Route::resource('/admin/partido','PartidosController');
	Route::resource('/admin/goleador','GoleadoresController');
	Route::resource('/admin/marcador','MarcadoresController');
	Route::resource('/admin/posicion','PosicionesController');
	Route::get  ('/admin/resultado/visitantes/{id}','ResultadosController@visitantes');
	Route::get  ('/admin/resultado/fecha/{id}','ResultadosController@fecha');
	Route::get   ('/admin/noticia/progress/{id}','NoticiasController@progress');
});

app/models/Partido.php
<?php

class Partido extends \Eloquent {
	protected $fillable = [];

	public function scopeUltimoPartido($query)
	{
		return $query
		->Join('marcadores','marcadores.partido_id','=','partidos.id')
		->where('dia','<=',date('Y-m-d'))
		->orderBy('dia','DESC')
		->limit(1);;
	}

	public function scopeProximoPartido($query)
	{
		return $query
		->where('dia','>=',date('Y-m-d'))
		->orderBy('dia','ASC')
		->limit(1);
	}

	public function scopePartidoEquipo($query)
	{
		$registrados = DB::table('marcadores')->select('partido_id')->lists('partido_id');
		return $query
		->leftJoin('equipos','equipos.id','=','partidos.equipo_id')
		->select(
			DB::raw('CONCAT(equipos.nombre," f-",partidos.fecha," (",partidos.dia,")") AS nombre'),
			'partidos.id'
			)
		->whereNotIn('partidos.id',$registrados)
		->orderBy('dia','DESC');
 	}

 	public function scopePartidos($query)
	{
		return $query
		->leftJoin('equipos','equipos.id','=','partidos.equipo_id')
		->select(
			DB::raw('CONCAT(equipos.nombre,"-",partidos.dia) AS nombre'),
			'partidos.id'
			)
		->orderBy('partidos.dia','DESC');
 	}

	public function equipo()
	{
		return $this->belongsTo('Equipo');
	}

	public function cancha()
	{
		return $this->belongsTo('Cancha');
	}

	public function torneo()
	{
		return $this->belongsTo('Torneo');
	}
}

app/controllers/PartidosController.php
<?php

class PartidosController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 * GET /partidos
	 *
	 * @return Response
	 */
	public function index()
	{
		$partidos = Partido::orderBy('dia','DESC')->get();
		return View::make('partido.index')
		->with('partidos',$partidos);
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /partidos/create
	 *
	 * @return Response
	 */
	public function create()
	{
		$equipos = Equipo::where('categoria_id', '1')->lists('nombre','id');
		$torneos = Torneo::lists('nombre','id');
		$canchas = Cancha::lists('nombre','id');
		return View::make('partido.create')
		->with('equipos',$equipos)
		->with('torneos',$torneos)
		->with('canchas',$canchas);
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /partidos
	 *
	 * @return Response
	 */
	public function store()
	{
		$partido = new Partido();
		$partido->equipo_id = Input::get('equipo_id');
		$partido->torneo_id = Input::get('torneo_id');
		$partido->cancha_id = Input::get('cancha_id');
		$partido->dia       = Input::get('dia');
		$partido->horario   = Input::get('horario');
		$partido->fecha     = Input::get('fecha');
		$partido->save();
		return Redirect::to('admin/partido')
		->with('alert-notice', 'Se ha agregado correctamente el partido.');
	}

	/**
	 * Display the specified resource.
	 * GET /partidos/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$partido = Partido::find($id);
		return View::make('partido.show')
		->with('partido',$partido);
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /partidos/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$partido = Partido::find($id);
		$equipos = Equipo::lists('nombre','id');
		$torneos = Torneo::lists('nombre','id');
		$canchas = Cancha::lists('nombre','id');
		return View::make('partido.edit')
		->with('partido',$partido)
		->with('equipos',$equipos)
		->with('torneos',$torneos)
		->with('canchas',$canchas);
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /partidos/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{

		$partido   = Partido::find($id);
		$partido->equipo_id = Input::get('equipo_id');
		$partido->torneo_id = Input::get('torneo_id');
		$partido->cancha_id = Input::get('cancha_id');
		$partido->dia       = Input::get('dia');
		$partido->horario   = Input::get('horario');
		$partido->fecha     = Input::get('fecha');
		$partido->save();
		return Redirect::to('admin/partido')
		->with('alert-warning', 'Se ha editado correctamente el partido.');
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /partidos/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$partido = Partido::find($id);
		$partido->delete();
		return Redirect::to('admin/partido')
		->with('alert-error', 'Se ha eliminado correctamente el partido.');
	}

}

app/views/partido/create.blade.php
@extends('layout.main')
@section('title')
Partidos Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-play"> Nuevo Partido</h2>
		</div>
		<div class="panel-body">
			{{ Form::open(array('route' => 'admin.partido.store')) }}
				@include('.partido.form')
				<button type="submit" class="btn btn-success pull-right">Registrar</button>
				<a class="btn btn-primary" href='{{ URL::previous() }}'>Regresar</a>
			{{ Form::close() }}
		</div>
	</div>
</div>
@stop

app/views/partido/edit.blade.php
@extends('layout.main')
@section('title')
Editar Partido Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-play"></span> Editar Partido</h2>
		</div>
		<div class="panel-body">
			{{ Form::model($partido,array('method' => 'PATCH', 'route' => array('admin.partido.update', $partido->id))) }}
				@include('partido.form')
				<button type="submit" class="btn btn-success pull-right">Actualizar</button>
				<a class="btn btn-primary" href='{{ URL::previous() }}'>Regresar</a>
			{{ Form::close() }}
		</div>
	</div>
</div>
@stop

app/views/partido/form.blade.php
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
	<div class="form-group">
		{{ Form::label('equipo_id' , 'Equipo')}}
		{{ Form::select('equipo_id', $equipos, null, array('class'=>'form-control'))}}<br>
		{{ Form::label('torneo_id' , 'Torneos')}}
		{{ Form::select('torneo_id', $torneos, null, array('class'=>'form-control'))}}<br>
		{{ Form::label('cancha_id' , 'Cancha')}}
		{{ Form::select('cancha_id', $canchas, null, array('class'=>'form-control'))}}
	</div>
</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
	<div class="form-group">
		{{ Form::label('dia')}}
		{{ Form::text('dia', null, array('class'=>'form-control datepicker'))}}<br>
		{{ Form::label('horario')}}
		{{ Form::text('horario', null, array('class'=>'form-control', 'id'=>'horario'))}}<br>
		{{ Form::label('fecha')}}
		{{ Form::number('fecha', null, array('class'=>'form-control','min'=>'4','max'=>'40'))}}
	</div>
</div>

app/views/partido/index.blade.php
@extends('layout.main')
@section('title')
Partidos Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-md-offset-1 col-lg-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-play"></span> Partidos</h2>
			{{ HTML::link(URL::to('/admin/partido/create'), '&nbsp;Nuevo', array('class' => 'btn btn-primary btn-sm pull-right glyphicon glyphicon-plus pull-right','style'=>'margin:-25px -10px 0 0')) }}
		</div>
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table">
					<thead>
						<tr>
							<th>vs Equipo</th>
							<th>Dia</th>
							<th>Horario</th>
							<th>Cancha</th>
							<th>Acciones</th>

						</tr>
					</thead>
					<tbody>
						@foreach($partidos as $partido)
						<tr>
							<td>{{ $partido->equipo->nombre }}</td>
							<td>{{ $partido->dia }}</td>
							<td>{{ date('h:i a',strtotime($partido->horario)) }}
							<td>{{ $partido->cancha->nombre }}</td>
							<td>
							{{ link_to_route('admin.partido.show','',$partido->id, array('class' => 'btn btn-success btn-xs glyphicon glyphicon-eye-open')) }}
							{{ link_to_route('admin.partido.edit','',$partido->id, array('class' => 'btn btn-warning btn-xs glyphicon glyphicon-pencil')) }}
							<a href="javascript:;" onclick="eliminaRegistro('{{URL::to('/admin/partido/'.$partido->id)}}','{{$partido->id}}');" class="btn btn-danger btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="eliminar"><i class="glyphicon glyphicon-trash"></i></a>
							{{ Form::open(array('method' => 'DELETE', 'route' => array('admin.partido.destroy', $partido->id),'id'=>$partido->id)) }}{{ Form::close() }}
							</td>
						</tr>
					@endforeach
					</tbody>
				</table>
				<br><br>
			</div>
		</div>
	</div>
</div>
<div id="dialog" title="¿Deseas eliminar el registro?">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span> Se eliminara permanentemente</p>
</div>
@stop
@section('css')
{{ HTML::style('css/dataTables.bs.css') }}
{{ HTML::style('css/toastr.css') }}
@stop
@section('js')
{{ HTML::script('js/dataTables.js') }}
{{ HTML::script('js/dataTables.bs.js') }}
{{ HTML::script('js/toastr.js') }}
@stop
@section('script')
<script type="text/javascript">
	jQuery(document).ready(function($)
	{
		$('table').DataTable({
			"lengthMenu": [[5, 10, -1],[5, 10, 'Todo']],
			"order": [[ 1, "desc" ]]
		});
		$("#dialog").dialog({
			resizable: false,
			height:170,
			modal: true,
			autoOpen: false,
			show: {
			effect: "bounce",
			duration: 500
			},
			hide: {
			effect: "fade",
			duration: 50
			}
		});
	});
function eliminaRegistro (url,id) {
	$( "#dialog" ).dialog( "open" );
	$( "#dialog" ).dialog({
		buttons: {
			"No": function() {
				$( this ).dialog( "close" );

			},
			"Si": function() {
				$( this ).dialog( "close" );
				$('#'+id).submit();
			}
		}
	});
}
</script>
@stop

app/views/partido/show.blade.php
@extends('layout.main')
@section('title')
Partido Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-play"> Partido</h2>
		</div>
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>vs {{ $partido->equipo->nombre }}</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Torneo:</td>
							<td>{{$partido->torneo->nombre}}</td>
						</tr>
						<tr>
							<td>cancha:</td>
							<td>{{$partido->cancha->nombre}}</td>
						</tr>
						<tr>
							<td>Dia:</td>
							<td>{{$partido->dia}}</td>
						</tr>
						<tr>
							<td>Horario:</td>
							<td>{{date('h:ia',strtotime($partido->horario))}}</td>
						</tr>
						<tr>
							<td>Fecha:</td>
							<td>{{$partido->fecha}}</td>
						</tr>
					</tbody>
				</table>
			</div>
			<a class="btn btn-primary" href='{{ URL::previous() }}'>Regresar</a>
		</div>
	</div>
</div>
@stop