app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
App::missing(function($exeption){
return Response::view('layout.error404');
});
App::after(function($request, $response)
{
$response->headers->set('Cache-Control','nocache, no-store, max-age=0, must-revalidate');
$response->headers->set('Pragma','no-cache');
$response->headers->set('Expires','Fri, 01 Jan 1990 00:00:00 GMT');
});
// Home
Route::get  ('/','HomeController@index');
Route::get  ('/jugadores','HomeController@players');
Route::get  ('/galeria','HomeController@gallery');
Route::get  ('/noticia/{id}','HomeController@noticia');
Route::get  ('/noticias','HomeController@noticias');
Route::get  ('/estadisticas','HomeController@estadisticas');
Route::get  ('/login','HomeController@login');
Route::post ('/loged', 'UsersController@loged');
Route::get  ('/logout', 'UsersController@logout');
// Administracion
Route::group(array('before' => 'Sentry|inGroup:admin'), function(){
	Route::resource('/admin/cancha', 'CanchasController');
	Route::resource('/admin/categoria', 'CategoriasController');
	Route::resource('/admin/equipo', 'EquiposController');
	Route::resource('/admin/torneo', 'TorneosController');
	Route::resource('/admin/noticia', 'NoticiasController');
	Route::resource('/admin/jugador', 'JugadoresController');
	Route::get     ('/admin/jugador/{id}/baja', 'JugadoresController@baja');
	Route::resource('/admin/slider', 'SlidersController');
	Route::resource('/admin/galeria', 'GaleriasController');
	Route::resource('/admin/partido','PartidosController');
	Route::resource('/admin/goleador','GoleadoresController');
	Route::resource('/admin/marcador','MarcadoresController');
	Route::resource('/admin/posicion','PosicionesController');
	Route::get  ('/admin/resultado/visitantes/{id}','ResultadosController@visitantes');
	Route::get  ('/admin/resultado/fecha/{id}','ResultadosController@fecha');
	Route::get   ('/admin/noticia/progress/{id}','NoticiasController@progress');
});

app/models/Torneo.php
<?php

class Torneo extends \Eloquent {
	protected $fillable = [];

	public function enfrentamiento()
	{
		return $this->belongsTo('Catalogo','enfrentamiento_id');
	}

	public function competicion()
	{
		return $this->belongsTo('Catalogo','competicion_id');
	}

	public function tipo()
	{
		return $this->belongsTo('Catalogo','tipoTorneo_id');
	}
}

app/controllers/TorneosController.php
<?php

class TorneosController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 * GET /torneos
	 *
	 * @return Response
	 */
	public function index()
	{
		$torneos = Torneo::all();
		return View::make('torneo.index')
		->with('torneos',$torneos);
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /torneos/create
	 *
	 * @return Response
	 */
	public function create()
	{
		$competiciones   = DB::table('catalogo')->where('metacatalogo_id', '1')->lists('nombre','id');
		$enfrentamientos = DB::table('catalogo')->where('metacatalogo_id', '2')->lists('nombre','id');
		$tipos           = DB::table('catalogo')->where('metacatalogo_id', '3')->lists('nombre','id');
		return View::make('torneo.create')
		->with('competiciones',$competiciones)
		->with('enfrentamientos',$enfrentamientos)
		->with('tipos',$tipos);
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /torneos
	 *
	 * @return Response
	 */
	public function store()
	{
		$tipoId                    = Input::get('tipoTorneo_id');
		$nombre                    = Catalogo::find($tipoId);
		$finicio                   = date_format(date_create(Input::get('finicio')),'y-m');
		$ffinal                    = date_format(date_create(Input::get('ffinal')),'y-m');
		$nombre                    = $nombre->nombre.' '.$finicio.'/'.$ffinal;
		$torneo                    = new Torneo();
		$torneo->nombre            = $nombre;
		$torneo->fechas            = Input::get('fechas');
		$torneo->tipoTorneo_id     = Input::get('tipoTorneo_id');
		$torneo->competicion_id    = Input::get('competicion_id');
		$torneo->enfrentamiento_id = Input::get('enfrentamiento_id');
		$torneo->finicio           = Input::get('finicio');
		$torneo->ffinal            = Input::get('ffinal');
		$torneo->save();
		return Redirect::to('admin/torneo')
		->with('flash_notice', 'Se ha agregado correctamente el torneo.');
	}

	/**
	 * Display the specified resource.
	 * GET /torneos/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$torneo = Torneo::find($id);
		return View::make('torneo.show')
		->with('torneo',$torneo);
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /torneos/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$competiciones   = DB::table('catalogo')->where('metacatalogo_id', '1')->lists('nombre','id');
		$enfrentamientos = DB::table('catalogo')->where('metacatalogo_id', '2')->lists('nombre','id');
		$tipos           = DB::table('catalogo')->where('metacatalogo_id', '3')->lists('nombre','id');
		$torneo = Torneo::find($id);
		return View::make('torneo.edit')
		->with('competiciones',$competiciones)
		->with('enfrentamientos',$enfrentamientos)
		->with('tipos',$tipos)
		->with('torneo',$torneo);
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /torneos/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$tipoId                    = Input::get('tipoTorneo_id');
		$nombre                    = Catalogo::find($tipoId);
		$finicio                   = date_format(date_create(Input::get('finicio')),'y-m');
		$ffinal                    = date_format(date_create(Input::get('ffinal')),'y-m');
		$nombre                    = $nombre->nombre.' '.$finicio.'/'.$ffinal;
		$torneo                    = Torneo::find($id);
		$torneo->nombre            = $nombre;
		$torneo->fechas            = Input::get('fechas');
		$torneo->tipoTorneo_id     = Input::get('tipoTorneo_id');
		$torneo->competicion_id    = Input::get('competicion_id');
		$torneo->enfrentamiento_id = Input::get('enfrentamiento_id');
		$torneo->finicio           = Input::get('finicio');
		$torneo->ffinal            = Input::get('ffinal');
		$torneo->save();
		return Redirect::to('admin/torneo')
		->with('flash_warning', 'Se ha editado correctamente el torneo.');
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /torneos/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$torneo = Torneo::find($id);
		$torneo->delete();
		return Redirect::to('admin/torneo')
		->with('flash_error', 'Se ha eliminado correctamente el torneo.');
	}

}

app/views/torneo/create.blade.php
@extends('layout.main')
@section('title')
Nuevo Torneo Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-calendar"></span> Nuevo Torneo</h2>
		</div>
		<div class="panel-body">
			{{ Form::open(array('route' => 'admin.torneo.store', 'files' => true)) }}
				@include('torneo.form')
				<button type="submit" class="btn btn-success pull-right">Registrar</button>
				<a class="btn btn-primary" href='{{ URL::previous() }}'>Regresar</a>
			{{ Form::close() }}
		</div>
	</div>
</div>
@stop
@section('script')
<script type="text/javascript">
	jQuery(document).ready(function($)
	{
		$('.timepicker').timepicker();	
	});
}
</script>
@stop

app/views/torneo/edit.blade.php
@extends('layout.main')
@section('title')
Editar {{ $torneo->nombre }} Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-calendar"></span> Editar Torneo {{ $torneo->nombre }}</h2>
		</div>
		<div class="panel-body">
			{{ Form::model($torneo,array('method'=>'PUT', 'route' => array('admin.torneo.update', $torneo->id))) }}
				@include('torneo.form')
				<button type="submit" class="btn btn-success pull-right">Actualizar</button>
				<a class="btn btn-primary" href='{{ URL::previous() }}'>Regresar</a>
			{{ Form::close() }}
		</div>
	</div>
</div>
@stop

app/views/torneo/form.blade.php
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
	<div class="form-group">
		{{ Form::label('fechas')}}
		{{ Form::number('fechas', null, array('class'=>'form-control','min'=>'4','max'=>'40'))}}<br>
		{{ Form::label('tipoTorneo_id' , 'Tipo')}}
		{{ Form::select('tipoTorneo_id', $tipos, null, array('class'=>'form-control'))}}<br>
		{{ Form::label('competicion_id','Competición')}}
		{{ Form::select('competicion_id', $competiciones, null, array('class'=>'form-control'))}}<br>
	</div>
</div>
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
	<div class="form-group">
		{{ Form::label('enfrentamiento_id','Enfrentamiento')}}
		{{ Form::select('enfrentamiento_id', $enfrentamientos, null, array('class'=>'form-control'))}}<br>
		{{ Form::label('finicio')}}
		{{ Form::text('finicio', null, array('class'=>'form-control'))}}<br>
		{{ Form::label('ffinal')}}
		{{ Form::text('ffinal', null, array('class'=>'form-control'))}}<br>
	</div>
</div>

app/views/torneo/index.blade.php
@extends('layout.main')
@section('title')
Torneoes Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-md-offset-1 col-lg-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-calendar"></span> Torneoes</h2>
			{{ HTML::link(URL::to('/admin/torneo/create'), '&nbsp;Nuevo', array('class' => 'btn btn-primary btn-sm pull-right glyphicon glyphicon-plus pull-right','style'=>'margin:-25px -10px 0 0')) }}
		</div>
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-hover" id="tabla">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Fechas</th>
							<th>Enfrentamiento</th>
							<th>Acciones</th>
						</tr>
					</thead>
					<tbody>
						@foreach($torneos as $torneo)
						<tr>
							<td>{{ $torneo->nombre }}</td>
							<td>{{ $torneo->fechas }}</td>
							<td>{{ $torneo->enfrentamiento->nombre }}</td>
							<td>
							{{ link_to_route('admin.torneo.show','',$torneo->id, array('class' => 'btn btn-success btn-xs glyphicon glyphicon-eye-open')) }}
							{{ link_to_route('admin.torneo.edit','',$torneo->id, array('class' => 'btn btn-warning btn-xs glyphicon glyphicon-pencil')) }}
							<a href="javascript:;" onclick="eliminaRegistro('{{URL::to('/admin/torneo/'.$torneo->id)}}','{{$torneo->id}}');" class="btn btn-danger btn-xs" data-toggle="tooltip" data-placement="top" data-original-title="eliminar"><i class="glyphicon glyphicon-trash"></i></a>
							{{ Form::open(array('method' => 'DELETE', 'route' => array('admin.torneo.destroy', $torneo->id),'id'=>$torneo->id)) }}{{ Form::close() }}
							</td>
						</tr>
					@endforeach
					</tbody>
				</table>
				<br><br>
			</div>
		</div>
	</div>
</div>
<div id="dialog" title="¿Deseas eliminar el registro?">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span> Se eliminara permanentemente</p>
</div>
@stop
@section('css')
{{ HTML::style('css/dataTables.bs.css') }}
{{ HTML::style('css/toastr.css') }}
@stop
@section('js')
{{ HTML::script('js/dataTables.js') }}
{{ HTML::script('js/dataTables.bs.js') }}
{{ HTML::script('js/toastr.js') }}
@stop
@section('script')
<script type="text/javascript">
	jQuery(document).ready(function($)
	{
		$('table').DataTable({
			"lengthMenu": [[5, 10, -1],[5, 10, 'Todo']]
		});
		$("#dialog").dialog({
			resizable: false,
			height:170,
			modal: true,
			autoOpen: false,
			show: {
			effect: "bounce",
			duration: 500
			},
			hide: {
			effect: "fade",
			duration: 50
			}
		});
	});
	function eliminaRegistro (url,id) {
	$( "#dialog" ).dialog( "open" );
	$( "#dialog" ).dialog({
		buttons: {
			"No": function() {
				$( this ).dialog( "close" );

			},
			"Si": function() {
				$( this ).dialog( "close" );
				$('#'+id).submit();
			}
		}
	});
}
</script>
@stop

app/views/torneo/show.blade.php
@extends('layout.main')
@section('title')
{{ $torneo->nombre }} Pumas Ruiz F.C.
@stop
@section('header')
	@include('layout.header')
@stop
@section('navbar')
	@include('layout.navbaradmin')
@stop
@section('content')
<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2">
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h2 class="panel-title"><span class="glyphicon glyphicon-calendar"> Torneo</h2>
		</div>
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>{{ $torneo->nombre }}</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Fechas:</td>
							<td>{{$torneo->fechas}}</td>
						</tr>
						<tr>
							<td>Tipo:</td>
							<td>{{$torneo->tipo->nombre}}</td>
						</tr>
						<tr>
							<td>Competición:</td>
							<td>{{$torneo->competicion->nombre}}</td>
						</tr>
						<tr>
							<td>Enfrentamiento:</td>
							<td>{{$torneo->enfrentamiento->nombre}}</td>
						</tr>
						<tr>
							<td>F. Inicial:</td>
							<td>{{$torneo->finicio}}</td>
						</tr>
						<tr>
							<td>F. Final:</td>
							<td>{{$torneo->ffinal}}</td>
						</tr>
					</tbody>
				</table>
			</div>
			<a class="btn btn-primary" href='{{ URL::previous() }}'>Regresar</a>
		</div>
	</div>
</div>
@stop